import type { Agent, Package, Review } from "@/lib/types";

export const mockAgents: Agent[] = [
  {
    id: "agent-1",
    name: "Wanderlust Travels",
    ownerUserId: "owner-1",
    phone: "123-456-7890",
    logoUrl: "https://picsum.photos/seed/a1/100/100",
    description: "Specializing in exotic beach destinations and adventure tours. We create unforgettable experiences.",
    verified: true,
    rating: 4.8,
    specialties: ["Adventure", "Honeymoon", "Luxury"],
    locations: ["Maldives", "Costa Rica", "Thailand"],
  },
  {
    id: "agent-2",
    name: "Mountain Peaks Agency",
    ownerUserId: "owner-2",
    phone: "234-567-8901",
    logoUrl: "https://picsum.photos/seed/a2/100/100",
    description: "Your go-to experts for trekking, hiking, and mountain climbing expeditions around the world.",
    verified: true,
    rating: 4.9,
    specialties: ["Trekking", "Nature", "Group Tours"],
    locations: ["Nepal", "Peru", "Switzerland"],
  },
  {
    id: "agent-3",
    name: "City Explorers Inc.",
    ownerUserId: "owner-3",
    phone: "345-678-9012",
    logoUrl: "https://picsum.photos/seed/a3/100/100",
    description: "Discover the world's most vibrant cities with our curated cultural and historical tours.",
    verified: true,
    rating: 4.7,
    specialties: ["Cultural", "Historical", "City Breaks"],
    locations: ["Rome", "Kyoto", "New York"],
  },
  {
    id: "agent-4",
    name: "Safari Adventures",
    ownerUserId: "owner-4",
    phone: "456-789-0123",
    logoUrl: "https://picsum.photos/seed/a4/100/100",
    description: "Experience the thrill of the wild with our expert-led safari trips in the heart of Africa.",
    verified: false,
    rating: 4.6,
    specialties: ["Safari", "Wildlife", "Photography"],
    locations: ["Kenya", "Tanzania", "South Africa"],
  },
];

export const mockPackages: Package[] = [
  {
    id: "pkg-1",
    agentId: "agent-1",
    title: "Magical Maldives Honeymoon",
    description: "Escape to a paradise of pristine beaches, crystal-clear waters, and luxurious overwater bungalows. A perfect romantic getaway.",
    price: 3500,
    durationDays: 7,
    itinerary: [
      { day: 1, title: "Arrival in Malé", description: "Transfer to your private island resort via speedboat." },
      { day: 2, title: "Snorkeling Adventure", description: "Explore vibrant coral reefs and marine life." },
      { day: 3, title: "Sunset Dolphin Cruise", description: "Enjoy a magical evening watching dolphins play." },
      { day: 4, title: "Spa & Relaxation", description: "Indulge in a couple's massage at the resort spa." },
      { day: 5, title: "Private Beach Dinner", description: "A romantic dinner under the stars." },
      { day: 6, title: "Watersports Fun", description: "Try jet skiing, paddleboarding, or kayaking." },
      { day: 7, title: "Departure", description: "Enjoy a final breakfast before heading home." },
    ],
    images: [
      "https://picsum.photos/seed/p1a/800/600",
      "https://picsum.photos/seed/p1b/800/600",
      "https://picsum.photos/seed/p1c/800/600",
    ],
    seatsAvailable: 10,
    destination: "Maldives",
    travelType: "Honeymoon",
  },
  {
    id: "pkg-2",
    agentId: "agent-2",
    title: "Everest Base Camp Trek",
    description: "Embark on a legendary trek to the foot of the world's highest peak. A journey of a lifetime for adventure enthusiasts.",
    price: 2200,
    durationDays: 14,
    itinerary: [
      { day: 1, title: "Arrival in Kathmandu", description: "Acclimatize and prepare for the trek." },
      { day: 2, title: "Flight to Lukla & Trek to Phakding", description: "Begin your Himalayan adventure." },
      { day: 3-5, title: "Trek to Namche Bazaar", description: "Acclimatization days and stunning views of Everest." },
      { day: 6-9, title: "Journey to Gorak Shep", description: "Trekking through beautiful Sherpa villages." },
      { day: 10, title: "Everest Base Camp", description: "Reach your goal and soak in the majestic atmosphere." },
      { day: 11-13, title: "Descent to Lukla", description: "Retrace your steps with a sense of accomplishment." },
      { day: 14, title: "Flight to Kathmandu & Departure", description: "End of your epic journey." },
    ],
    images: [
      "https://picsum.photos/seed/p2a/800/600",
      "https://picsum.photos/seed/p2b/800/600",
      "https://picsum.photos/seed/p2c/800/600",
    ],
    seatsAvailable: 15,
    destination: "Nepal",
    travelType: "Trekking",
  },
  {
    id: "pkg-3",
    agentId: "agent-3",
    title: "Ancient Rome & Vatican City",
    description: "Walk through history as you explore the iconic landmarks of Ancient Rome and the spiritual heart of the Vatican City.",
    price: 1800,
    durationDays: 5,
    itinerary: [
      { day: 1, title: "Arrival in Rome", description: "Check into your hotel and enjoy a welcome dinner." },
      { day: 2, title: "The Roman Forum & Colosseum", description: "A guided tour of ancient wonders." },
      { day: 3, title: "Vatican City Tour", description: "Visit St. Peter's Basilica, the Vatican Museums, and the Sistine Chapel." },
      { day: 4, title: "Pantheon & Trevi Fountain", description: "Explore more of Rome's iconic sites and enjoy some gelato." },
      { day: 5, title: "Departure", description: "Transfer to the airport for your flight home." },
    ],
    images: [
      "https://picsum.photos/seed/p3a/800/600",
      "https://picsum.photos/seed/p3b/800/600",
      "https://picsum.photos/seed/p3c/800/600",
    ],
    seatsAvailable: 20,
    destination: "Italy",
    travelType: "Cultural",
  },
  {
    id: "pkg-4",
    agentId: "agent-1",
    title: "Costa Rican Rainforest Adventure",
    description: "Immerse yourself in the lush biodiversity of Costa Rica. Zipline through canopies, hike to waterfalls, and spot exotic wildlife.",
    price: 2500,
    durationDays: 8,
    itinerary: [
      { day: 1, title: "Arrival in San José", description: "Transfer to your eco-lodge near Arenal Volcano." },
      { day: 2, title: "Arenal Volcano Hike", description: "Hike the trails around the majestic volcano." },
      { day: 3, title: "Ziplining & Hanging Bridges", description: "Experience the rainforest from above." },
      { day: 4, title: "La Fortuna Waterfall", description: "Swim in the refreshing pool of a stunning waterfall." },
      { day: 5, title: "Travel to Monteverde", description: "Journey to the famous Cloud Forest." },
      { day: 6, title: "Monteverde Cloud Forest Reserve", description: "Guided nature walk to spot wildlife." },
      { day: 7, title: "Coffee Plantation Tour", description: "Learn about and taste world-famous Costa Rican coffee." },
      { day: 8, title: "Departure from San José", description: "Head home with amazing memories." },
    ],
    images: [
      "https://picsum.photos/seed/p4a/800/600",
      "https://picsum.photos/seed/p4b/800/600",
    ],
    seatsAvailable: 12,
    destination: "Costa Rica",
    travelType: "Adventure",
  },
];

export const mockReviews: Review[] = [
  {
    id: "review-1",
    userId: "user-1",
    agentId: "agent-1",
    rating: 5,
    comment: "Wanderlust Travels planned the most incredible honeymoon for us! Every detail was perfect.",
    createdAt: new Date("2023-10-15"),
  },
  {
    id: "review-2",
    userId: "user-2",
    agentId: "agent-2",
    rating: 5,
    comment: "The Everest Base Camp trek was challenging but so rewarding. Mountain Peaks Agency's guides were professional and supportive.",
    createdAt: new Date("2023-11-20"),
  },
   {
    id: "review-3",
    userId: "user-3",
    agentId: "agent-3",
    rating: 4,
    comment: "Great tour of Rome. Very knowledgeable guides. Could have been slightly better organized.",
    createdAt: new Date("2023-09-05"),
  },
];
